services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
    networks:
      - fcontrol

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    networks:
      - fcontrol

networks:
  fcontrol:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
